### PR TITLE
Highlight messages that trip your dingwords

### PR DESCRIPTION
**Pull request by zarvox**
This is kinda a starting point for discussion.  I'm not totally sold on this specific appearance for this, but I do like the idea of having "the message that summoned me to a puzzle" having something that indicates the specific message in the log as noteworthy.

I'm open to feedback on the idea, including "this is ugly/a bad idea; don't do this".  Thoughts?

### CODE REVIEW

**Review by ebroder — APPROVED** [review]
This seems fine to me. I think it would be nice if we also highlighted the specific substring that matched (especially to help with debugging why a particular dingword is firing), but I'm not sure I know how to integrate that offhand with the v2 content.

**Comment by zarvox** [comment]
I can think of a way I might achieve that in `ChatMessageV2` -- basically, search for dingwords in each range of text that we would render raw, and wrap the matching substring range in a `background-color`'d subspan?  I'll give it a shot later today.

**Comment by ebroder** [comment]
I guess you can...decorate the dingword, and then this basically just works?

**Comment by zarvox** [comment]
Can't use `decorate` outside of the editor.

**Pull request merged**
