### PR TITLE
`meteor update` to 2.5

### PR DESCRIPTION
**Pull request by zarvox**
Log:

Changes to your project's package version selections from updating the release:

accounts-base*             upgraded from 1.9.0 to 2.2.0
accounts-password*         upgraded from 1.7.1 to 2.2.0
autoupdate                 upgraded from 1.7.0 to 1.8.0
babel-compiler             upgraded from 7.6.2 to 7.7.0
callback-hook              upgraded from 1.3.0 to 1.4.0
ddp-client                 upgraded from 2.4.1 to 2.5.0
ddp-rate-limiter           upgraded from 1.0.9 to 1.1.0
ddp-server                 upgraded from 2.3.3 to 2.5.0
dynamic-import             upgraded from 0.6.0 to 0.7.2
ecmascript                 upgraded from 0.15.1 to 0.16.0
ecmascript-runtime         upgraded from 0.7.0 to 0.8.0
ecmascript-runtime-client  upgraded from 0.11.1 to 0.12.1
ecmascript-runtime-server  upgraded from 0.10.1 to 0.11.0
email                      upgraded from 2.0.0 to 2.2.0
google-oauth               upgraded from 1.3.0 to 1.4.1
hot-module-replacement     upgraded from 0.2.1 to 0.4.0
launch-screen              upgraded from 1.2.1 to 1.3.0
livedata                   removed from your project
logging                    upgraded from 1.2.0 to 1.3.1
meteor                     upgraded from 1.9.3 to 1.10.0
meteor-base                upgraded from 1.4.0 to 1.5.1
minifier-css               upgraded from 1.5.4 to 1.6.0
minifier-js                upgraded from 2.6.0 to 2.7.1
minimongo                  upgraded from 1.6.2 to 1.7.0
modern-browsers            upgraded from 0.1.5 to 0.1.7
modules                    upgraded from 0.16.0 to 0.17.0
modules-runtime-hot        upgraded from 0.13.0 to 0.14.0
mongo                      upgraded from 1.11.1 to 1.13.0
npm-bcrypt                 removed from your project
npm-mongo                  upgraded from 3.9.0 to 3.9.1
oauth*                     upgraded from 1.3.2 to 2.1.0
oauth2                     upgraded from 1.3.0 to 1.3.1
promise                    upgraded from 0.11.2 to 0.12.0
react-fast-refresh         upgraded from 0.1.1 to 0.2.0
routepolicy                upgraded from 1.1.0 to 1.1.1
server-render              upgraded from 0.3.1 to 0.4.0
service-configuration      upgraded from 1.0.11 to 1.3.0
socket-stream-client       upgraded from 0.3.3 to 0.4.0
srp                        removed from your project
standard-minifier-css      upgraded from 1.7.3 to 1.7.4
standard-minifier-js       upgraded from 2.6.1 to 2.7.1
typescript                 upgraded from 4.2.2 to 4.4.0
webapp                     upgraded from 1.10.1 to 1.13.0

* These packages have been updated to new versions that are not backwards
compatible.
jolly-roger: updated to Meteor 2.5.

Changes to your project's package version selections from updating package versions:

aldeed:collection2    upgraded from 3.4.1 to 3.5.0
meteortesting:mocha   upgraded from 2.0.2 to 2.0.3
percolate:migrations  upgraded from 1.0.2 to 1.0.3
react-meteor-data     upgraded from 2.3.1 to 2.3.3

The following top-level dependencies were not updated to the very latest version available:
 * http 1.4.4 (2.0.0 is available)

Newer versions of the following indirect dependencies are available:
 * coffeescript 1.0.17 (2.4.1 is available)
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.
If the packages do not upgrade after this, this could mean
that there is a newer version of Meteor which the package
requires, but it not yet recommended or that some package
dependencies are not up to date and don't allow you to get
the latest package version.

### CODE REVIEW

**Comment by zarvox** [comment]
Okay, I tried doing the Docker build & run locally and with the node upgrade, nothing went horribly wrong, so this is probably good to go

**Review by ebroder — APPROVED** [review]
LGTM

Reading through the changelog, it looks like the `HTTP` package has been deprecated in favor of `fetch` (or a [`fetch` polyfill](https://atmospherejs.com/meteor/fetch)); we should probably pick that up at some point

**Comment by ebroder** [comment]
(Also I think it might now be possible to switch over to using SES instead of Mailgun which would make me very happy)

**Comment by zarvox** [comment]
Yep, the `HTTP` package changes are actually one thing that didn't auto-update here -- we can dive in by upgrading to `http 2.0.0`, but they're not forcing that out yet.

And yeah it does look like they have wider support for various email-sending services, which is rad.

**Pull request merged**
